name: My workflow

on:
  schedule:
    - cron: "36 17 * * *"

permissions:
  contents: write
    

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      - name: Check out StarRailData
        uses: actions/checkout@v3
        with:
          repository: Dimbreath/StarRailData
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          path: StarRailData

      - id: lastcommit
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          repository: Dimbreath/StarRailData
          branch: master
          token: ${{ secrets.PUBLIC_REPO_PAT }}

      - name: Run update script
        run: npm run update-data -- --version ${{ steps.lastcommit.outputs.description }}

      - name: Check for changes
        run: git diff --quiet || exit 0
      - name: Commit changes (if any)
        run: |
          git config --global user.name "theBowja"
          git config --global user.email "theBowja@users.noreply.github.com"
          git add --all
          git commit -am "Automated update for ${{ steps.lastcommit.outputs.description }}"
          git push
        if: ${{ success() }}  # Only commit if previous step succeeds (no changes)